on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.13'
jobs:
  analyze:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ inputs.python-version }}
      - run: uv sync
      - run: uv run invoke test.coverage --xml
      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage.xml
          format: cobertura
